--- 
abstract: Extract Feature Sentences From HTML Documents
author: "Takeshi Miki <miki@cpan.org> "
build_requires: 
  FindBin: 0
  Path::Class: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-Feature
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::Accessor::Fast: 0
  Encode::Guess: 0
  HTML::TreeBuilder: 0
  HTTP::Response::Encoding: 0
  LWP::UserAgent: 0
  List::Util: 0
  Scalar::Util: 0
  Statistics::Lite: 0
  UNIVERSAL::require: 0
tests: t/*.t t/*/*.t
version: 2.0.2
