# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Feature
version:      1.0.3
version_from: lib/HTML/Feature.pm
installdirs:  site
requires:
    Encode:                        2.12
    Encode::Guess:                 2
    HTML::TreeBuilder:             3.23
    LWP::Simple:                   1.41
    Statistics::Lite:              2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
